---
 - name: copy php to web clusters
   copy: src=../files/php-7.0.2.tar.gz dest=/usr/local/src
 - name: copy install_shell to client
   copy: src=../files/install_php7.sh dest=/usr/local/src
 - name: install mysql
   shell: /bin/bash /usr/local/src/install_php7.sh
